const defaultControllers: [any] = [
  {
    name: 'Default #1',
    controls: [
      {
        type: 'Button',
        x: 10,
        y: 20,
        width: 80,
        height: 40,
        text: 'Search',
      },
      {
        type: 'Button',
        x: 100,
        y: 20,
        width: 80,
        height: 40,
        text: 'Maps',
      },
      {
        type: 'Button',
        x: 190,
        y: 20,
        width: 80,
        height: 40,
        text: 'Calendar',
      },
      {
        type: 'Label',
        x: 10,
        y: 80,
        width: 50,
        height: 20,
        text: 'Date',
      },
      {
        type: 'Label',
        x: 100,
        y: 80,
        width: 50,
        height: 20,
        text: 'Day',
      },
      {
        type: 'Label',
        x: 190,
        y: 80,
        width: 50,
        height: 20,
        text: 'Time',
      },
      {
        type: 'Slider',
        x: 10,
        y: 140,
        width: 280,
        value: 50,
      },
    ],
  },
];
defaultControllers.push({
  name: 'Default #2',
  controls: [
    {
      type: 'Button',
      x: 10,
      y: 20,
      width: 200,
      height: 150,
      text: 'Search',
    },
    {
      type: 'Button',
      x: 220,
      y: 20,
      width: 200,
      height: 150,
      text: 'Maps',
    },
    {
      type: 'Label',
      x: 10,
      y: 200,
      width: 200,
      height: 150,
      text: 'Date',
    },
    {
      type: 'Label',
      x: 250,
      y: 200,
      width: 200,
      height: 150,
      text: 'Day',
    },
    {
      type: 'Slider',
      x: 10,
      y: 400,
      width: 280,
      value: 50,
    },
    {
      type: 'Slider',
      x: 10,
      y: 500,
      width: 280,
      value: 50,
    },
  ],
});
export { defaultControllers };
